// Global styles (Next.js requires global CSS to be imported here)
import '../src/style.css'
import '../src/views/home.css'
import '../src/views/not-found.css'
import '../src/views/merch-page.css'
import '../src/views/gallery-page.css'
import '../src/views/event-page.css'
import '../src/views/about-page.css'
import '../src/views/contact-page.css'
import '../src/views/classes-page.css'
import '../src/components/navbar.css'
import '../src/components/navbar2.css'
import '../src/components/navbar3.css'
import '../src/components/footer.css'
import '../src/components/timetable.css'
import '../src/components/reviews.css'
import '../src/components/question1.css'
import '../src/components/private-class-info.css'
import '../src/components/pom-info.css'
import '../src/components/musical-theare-info.css'
import '../src/components/merch-banner.css'
import '../src/components/meet-info.css'
import '../src/components/map.css'
import '../src/components/home-page-classes.css'
import '../src/components/home-class-component.css'
import '../src/components/google-review.css'
import '../src/components/gallery3.css'
import '../src/components/gallery2.css'
import '../src/components/gallery1.css'
import '../src/components/gallery-banner.css'
import '../src/components/features17.css'
import '../src/components/feature-card4.css'
import '../src/components/feature-card3.css'
import '../src/components/feature-card2.css'
import '../src/components/feature-card.css'
import '../src/components/events-feature.css'
import '../src/components/events-banner.css'
import '../src/components/event-banner.css'
import '../src/components/contact3.css'
import '../src/components/contact-form.css'
import '../src/components/contact-banner.css'
import '../src/components/component.css'
import '../src/components/coming-soon.css'
import '../src/components/classes-banner.css'
import '../src/components/about-us-banner.css'

export default function App({ Component, pageProps }) {
  return <Component {...pageProps} />
}
